### ISSUE TITLE
Question: Best way for a custom tag?

### ISSUE THREAD

**Issue by vsoch** [CircleCI-Public/circleci-orbs#105]
Hey circle!

For the docker-publish orb, I'm wondering what the best / easiest way is to tag a docker container with some string produced at runtime. For example I'd want to build the image (with latest)

```
docker build -t user/repo .
```
Then derive a tag by pinging the software inside:

```bash
DOCKER_TAG=$(docker run user/repo --version)
```
Then tag the container:

```bash
docker tag user/repo:latest user/repo:$DOCKER_TAG
```
and then push both of them

```bash
docker push user/repo
```
I have a recipe to do this the old way (without an orb) but I'm hoping there is a way to do it with orbs because I like them a lot. :)

**Comment by vsoch** [comment]
Actually I have an idea - I can use a post build hook to see if I can tag the image and push there.

**Comment by vsoch** [comment]
Yeah that totally worked! Here is what I did if anyone else needs in the future. The idea here is that we want to build on pull requests, but not on merge to master. The first block here will build the container, and preview the tag based on querying the software inside:

```yaml
version: 2.1

orbs:
  # https://circleci.com/orbs/registry/orb/circleci/docker-publish
  docker-publish: circleci/docker-publish@0.1.3
workflows:

  # This workflow will be run on all branches but master (to test)
  build_without_publishing_job:
    jobs:
      - docker-publish/publish:
          image: singularityhub/sif
          deploy: false
          tag: latest
          filters:
            branches:
              ignore: master
          after_build:
            - run:
                name: Preview Docker Tag for Build
                command: |
                   DOCKER_TAG=$(docker run singularityhub/sif:latest --version)
                   echo "Version for Docker tag is ${DOCKER_TAG}"
```
[Here is the run](https://circleci.com/gh/singularityhub/sif/19)

And this second block is the same, but deploy is set to True (This is the default) and we add a docker tag command.

```yaml
  # This workflow will deploy images on merge to master only
  docker_with_lifecycle:
    jobs:
      - docker-publish/publish:
          image: singularityhub/sif
          tag: latest
          filters:
            branches:
             only: master
          after_build:
            - run:
                name: Publish Docker Tag with SIF Python Version
                command: |
                   DOCKER_TAG=$(docker run singularityhub/sif:latest --version)
                   echo "Version for Docker tag is ${DOCKER_TAG}"
                   docker tag singularityhub/sif:latest singularityhub/sif:${DOCKER_TAG}
```
[Run is here](https://circleci.com/gh/singularityhub/sif/22)

I originally had a docker push in that run block, but actually it isn't needed because the final push will include both containers in the namespace (singularityhub/sif) will push both. Huzzah! Here are the containers on Docker Hub -> https://cloud.docker.com/u/singularityhub/repository/registry-1.docker.io/singularityhub/sif
