### ISSUE TITLE
Could we have some usage examples for "approval required notification" in slack orb?

### ISSUE THREAD

**Issue by stig** [CircleCI-Public/circleci-orbs#115]
### Orb version

circleci/slack@1.1.0

### What happened

I can't figure out how to add the `slack/approval-notification` into my workflow if it's not the very first one. I see how I can get this workflow:

> slack/approval-notification -> hold_for_approval -> deploy_prod

But, what I want is this workflow:

> build -> test -> deploy_dev -> slack/approval-notification -> hold_for_approval -> deploy_prod

### Expected behavior

I think the `slack/approval-notification` job needs the ability to specify a list of things it requires before it triggers. Perhaps it already exists, but it certainly isn't clear from the documentation how you would use it!

**Comment by jkzilla** [comment]
Hi @stig - I just tried this out yesterday with the hello-build orb - Can you post your config minus any sensitive information such as slack user ID? Not sure if this helps but posting just in case:

```version: 2.1

orbs:
    hello: circleci/hello-build@0.0.8 # uses the circleci/buildpack-deps Docker image
    slack: circleci/slack@1.1.0
workflows:
    "Hello Workflow":
        jobs:
          - hello/hello-build
          - slack/approval-notification:
              mentions: 'U<this is your slack user ID>M'
              webhook: $SLACK_WEBHOOK```

**Comment by stig** [comment]
@jkzilla thank you for your comment. I can see how that works, because neither of the two jobs don't depend on anything. I want to make the approval notification only trigger if hello-build passes, and I cannot see how to do that.

**Comment by tommybo-entur** [comment]
A little late response, but it's just like any other job in a workflow:
```
workflows:
  "Verify component":
    jobs:
      -test
      -integration-test
      - slack/approval-notification:
          webhook: https://MYHOOK
          message: "Deploy pending approval: https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID"
          requires:
            - test
            - integration-test
```
