### ISSUE TITLE
AWS s3 ORB Overwrite not working

### ISSUE THREAD

**Issue by avivbueno** [CircleCI-Public/circleci-orbs#156]
### Orb version
2.1
aws-s3 1.0.8

### What happened
When overwrite set to true throws an error:
aws s3 sync \
  bucket s3://aviv-ci-test \
  --acl public-read
--cache-control "max-age=86400"
 \
  --delete
upload: bucket/build_asset1.txt to s3://aviv-ci-test/build_asset1.txt
/bin/bash: line 3: --cache-control: command not found
Exited with code 127### Expected behavior

Delete the previous files on the bucket and sync

**Comment by iynere** [comment]
@avivbueno can you share a link to a job where you're seeing this behavior ? thank you !

**Comment by avivbueno** [comment]
https://circleci.com/gh/avivbueno/citest/10

Screenshot: https://imgur.com/a/npqlN6W

config file: https://github.com/avivbueno/citest/blob/master/.circleci/config.yml

**Comment by iynere** [comment]
thank you !! @avivbueno 

looks like this is a simple bash syntax issue—should be easy to fix, 1 sec

**Comment by iynere** [comment]
@avivbueno i believe this is happening because you are passing a multi-line string argument to the `arguments` parameter, without including `\` to allow bash to interpolate the multiple lines

can you try it like this ?

```
      - aws-s3/sync:
          from: bucket
          to: 's3://aviv-ci-test'
          aws-region: AWS_REGION_BLUE
          overwrite: true
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
```

may just be an issue of documenting precisely how users should pass single- or multi-line values to that parameter. thanks !
